[package]
name = "voices-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.58"
byteorder = "1"
cpal = "0.13.5"
crossbeam = "0.8.2"
futures-util = "0.3.21"
hound = "3.4.0"
prost = "0.11.0"
prost-types = "0.11.0"
rodio = "0.15.0"
serde = { version = "1.0.140", features = ["derive"] }
serde_json = "1.0.82"
tracing = { version = "0.1.36", features = ["log"] }
tracing-subscriber = { version = "0.3.15", features = ["env-filter"] }
tungstenite = { version = "0.17.3", features = ["rustls"] }
uuid = { version = "1.1.2", features = ["v4", "serde"] }

[build-dependencies]
anyhow = "1.0.58"
prost-build = "0.11.0"
