[package]
name = "voices-voice-crypto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xsalsa20poly1305 = { version = "0.9.1", features = ["std"] }
